do

	XPRACTICE.MULTIPLAYERV2.PREFIX="XP"

	if(not XPRACTICE.MULTIPLAYERV2.LISTENER)then
		XPRACTICE.MULTIPLAYERV2.LISTENER=CreateFrame("Frame")
		XPRACTICE.MULTIPLAYERV2.LISTENER:RegisterEvent("CHAT_MSG_ADDON")
		XPRACTICE.MULTIPLAYERV2.LISTENER:RegisterEvent("GROUP_ROSTER_UPDATE")
		XPRACTICE.MULTIPLAYERV2.LISTENER:SetScript("OnEvent",XPRACTICE.MULTIPLAYERV2.EventHandler)
		C_ChatInfo.RegisterAddonMessagePrefix(XPRACTICE.MULTIPLAYERV2.PREFIX)
	end	

	XPRACTICE.MULTIPLAYERV2.PREFIX_SAY="XP_log_say"
	XPRACTICE.MULTIPLAYERV2.PREFIX_YELL="XP_log_yell"

	XPRACTICE.MULTIPLAYERV2.LISTENER:RegisterEvent("CHAT_MSG_ADDON_LOGGED")
	C_ChatInfo.RegisterAddonMessagePrefix(XPRACTICE.MULTIPLAYERV2.PREFIX_SAY)
	C_ChatInfo.RegisterAddonMessagePrefix(XPRACTICE.MULTIPLAYERV2.PREFIX_YELL)
	XPRACTICE.MULTIPLAYERV2.LISTENER:SetScript("OnEvent",XPRACTICE.MULTIPLAYERV2.EventHandler)
	
	
	
	
end