local NAME, L = ...
L.sounds = {}
L.sounds["CSC Notification 49"] = "CSC_all-cards-on-table.mp3"
L.sounds["CSC Notification 50"] = "CSC_digital-spit.mp3"
L.sounds["CSC Notification 51"] = "CSC_done-for-you.mp3"
L.sounds["CSC Notification 52"] = "CSC_gesture.mp3"
L.sounds["CSC Notification 53"] = "CSC_glitch-in-the-matrix.mp3"
L.sounds["CSC Notification 54"] = "CSC_glitchy-tone.mp3"
L.sounds["CSC Notification 55"] = "CSC_hollow.mp3"
L.sounds["CSC Notification 56"] = "CSC_i-demand-attention.mp3"
L.sounds["CSC Notification 57"] = "CSC_inquisitiveness.mp3"
L.sounds["CSC Notification 58"] = "CSC_insight.mp3"
L.sounds["CSC Notification 59"] = "CSC_just-like-magic.mp3"
L.sounds["CSC Notification 60"] = "CSC_long-expected.mp3"
L.sounds["CSC Notification 61"] = "CSC_lots-of-data.mp3"
L.sounds["CSC Notification 62"] = "CSC_meaty.mp3"
L.sounds["CSC Notification 63"] = "CSC_news-bringer.mp3"
L.sounds["CSC Notification 64"] = "CSC_on-target.mp3"
L.sounds["CSC Notification 65"] = "CSC_pedantic-2.mp3"
L.sounds["CSC Notification 66"] = "CSC_question-raised.mp3"
L.sounds["CSC Notification 67"] = "CSC_rvrb.mp3"
L.sounds["CSC Notification 68"] = "CSC_scissors.mp3"
L.sounds["CSC Notification 69"] = "CSC_scratch.mp3"
L.sounds["CSC Notification 70"] = "CSC_shoot-em.mp3"
L.sounds["CSC Notification 71"] = "CSC_sorted.mp3"
L.sounds["CSC Notification 72"] = "CSC_system-fault.mp3"
L.sounds["CSC Notification 73"] = "CSC_tweet.mp3"
L.sounds["CSC Notification 74"] = "CSC_wee-tziu.mp3"
L.sounds["CSC Notification 75"] = "CSC_what.mp3"



