name: Package and upload

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECHO_TOKEN: ${{ secrets.ECHO_TOKEN }}
      GRIM_EXTERNAL_TOKEN : ${{ secrets.GRIM_TOKEN }}
      DRADUX_EXTERNAL_TOKEN : ${{ secrets.DRADUX_TOKEN }}

    steps:
      - name: Checkout addon
        uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: Set github config for Grim
        run: git config --global url."https://grimoja:${GRIM_EXTERNAL_TOKEN}@github.com/Grimonja/".insteadOf "https://github.com/Grimonja/"

      - name: Set github config for Dradux
        run: git config --global --add url."https://Dradux-dev:${DRADUX_EXTERNAL_TOKEN}@github.com/Dradux-dev/".insteadOf "https://github.com/Dradux-dev/"

      - name: Package
        uses: ./.github/packager
