do

	XPRACTICE.MULTIPLAYER.PREFIX="XP"
	XPRACTICE.MULTIPLAYER.PREFIX_SAY="XP_log_say"
	XPRACTICE.MULTIPLAYER.PREFIX_YELL="XP_log_yell"

	if(not XPRACTICE.MULTIPLAYER.LISTENER)then
		XPRACTICE.MULTIPLAYER.LISTENER=CreateFrame("Frame")
		XPRACTICE.MULTIPLAYER.LISTENER:RegisterEvent("CHAT_MSG_ADDON")
		XPRACTICE.MULTIPLAYER.LISTENER:RegisterEvent("GROUP_ROSTER_UPDATE")
		XPRACTICE.MULTIPLAYER.LISTENER:RegisterEvent("CHAT_MSG_ADDON_LOGGED")
		C_ChatInfo.RegisterAddonMessagePrefix(XPRACTICE.MULTIPLAYER.PREFIX_SAY)
		C_ChatInfo.RegisterAddonMessagePrefix(XPRACTICE.MULTIPLAYER.PREFIX_YELL)
		C_ChatInfo.RegisterAddonMessagePrefix(XPRACTICE.MULTIPLAYER.PREFIX)
		XPRACTICE.MULTIPLAYER.LISTENER:SetScript("OnEvent",XPRACTICE.MULTIPLAYER.EventHandler)			
	end	
	
	


	
	
	
	
end